from enum import Enum

class OperationType(Enum):
    OPERATION_TYPE_GAME = 1
    OPERATION_TYPE_GAMES_DTO = 2
    OPERATION_TYPE_REVIEW = 4
    OPERATION_TYPE_PLATFORM_DTO = 5
    OPERATION_TYPE_GENRE_DTO = 6
    OPERATION_TYPE_STR = 27
