@startuml
actor Cliente

control Middleware
control ExchangeFanout
control ExchangeDirect
control NodeWorker

entity Mensaje
entity Cola
entity Resultado

Cliente --> Middleware : Enviar Solicitud
Middleware --> ExchangeFanout : Distribuir Mensaje (Fanout)
Middleware --> ExchangeDirect : Distribuir Mensaje (Direct)
ExchangeFanout --> Cola : Enviar a Cola
ExchangeDirect --> Cola : Enviar a Cola
Cola --> NodeWorker : Enviar a NodeWorker
NodeWorker --> Resultado : Procesar Mensaje
Resultado --> Cliente : Enviar Resultado
@enduml