
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    

  medic_0:
    container_name: medic_0
    image: leader:latest
    entrypoint: python3 -u /app/system/leader/main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_NAME=medic_0
      - NODE_INSTANCE_NAME=medic_0
      - NODE_ID=500
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    
  medic_1:
    container_name: medic_1
    image: leader:latest
    entrypoint: python3 -u /app/system/leader/main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_NAME=medic_1
      - NODE_INSTANCE_NAME=medic_1
      - NODE_ID=501
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic_0:
        condition: service_started
    
  medic_2:
    container_name: medic_2
    image: leader:latest
    entrypoint: python3 -u /app/system/leader/main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_NAME=medic_2
      - NODE_INSTANCE_NAME=medic_2
      - NODE_ID=502
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic_1:
        condition: service_started
    
  medic_3:
    container_name: medic_3
    image: leader:latest
    entrypoint: python3 -u /app/system/leader/main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_NAME=medic_3
      - NODE_INSTANCE_NAME=medic_3
      - NODE_ID=503
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic_2:
        condition: service_started
    

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 -u /app/client/main.py
    volumes:
      - ./data/games.csv:/data/games.csv
      - ./data/dataset.csv:/data/dataset.csv
      - ./data/responses:/data/responses
      - ./persistent:/persistent
    environment:
      - QUERIES_EXECUTED=[1, 2, 3, 4, 5]  
      - PERCENT_OF_FILE_FOR_USE_BY_EXECUTION=0.1
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - HOSTNAME=gateway
      - NODE_NAME=client1
      - NODE_ID=100
      - SEND_REVIEWS=1
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    
  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 -u /app/system/controllers/gateway/main.py
    networks:
        - system_network
    restart: on-failure
    volumes:
      - ./persistent:/persistent
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=gateway
        - NODE_INSTANCE_NAME=gateway
        - NODE_ID=101
        - SOURCE=Output
        - SINK=DataRaw
        - AMOUNT_OF_QUERIES=5
    depends_on:
      rabbitmq:
        condition: service_healthy
      filterbasic_0:
        condition: service_started
        
  filterbasic_0:
    container_name: filterbasic_0
    image: filterbasic:latest
    entrypoint: python3 -u /app/system/controllers/filters/filterBasic/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectq1_0:
            condition: service_started
        selectq2345_0:
            condition: service_started
        filterscorepositive_0:
            condition: service_started
        filterscorenegative_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterbasic
        - NODE_INSTANCE_NAME=filterbasic_0
        - NODE_ID=102
        - AMOUNT_OF_NODES=1
        - SOURCE=DataRaw
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=DataParsed
        - SINK_TYPE=topic
        
  selectq1_0:
    container_name: selectq1_0
    image: select:latest
    entrypoint: python3 -u /app/system/controllers/select/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        platformcounter_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectq1
        - NODE_INSTANCE_NAME=selectq1_0
        - NODE_ID=103
        - AMOUNT_OF_NODES=1
        - SOURCE=DataParsed
        - SOURCE_KEY=games
        - SOURCE_TYPE=topic
        - SINK=GamesPlatform
        - SINK_TYPE=direct
        - SELECT=2
        - SEND_MODULO=1
        
  platformcounter_0:
    container_name: platformcounter_0
    image: platformcounter:latest
    entrypoint: python3 -u /app/system/controllers/groupers/platformCounter/main.py
    networks:
        - system_network
    volumes:
      - ./persistent:/persistent
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        platformreducer:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=platformcounter
        - NODE_INSTANCE_NAME=platformcounter_0
        - NODE_ID=104
        - AMOUNT_OF_NODES=1
        - SOURCE=GamesPlatform
        - SOURCE_KEY=104
        - SOURCE_TYPE=direct
        - SINK=CountByPlatform
        - SINK_TYPE=direct
        - SOURCE_NAME=platformcounter104
    
  platformreducer:
    container_name: platformreducer
    image: platformcounter:latest
    entrypoint: python3 -u /app/system/controllers/groupers/platformCounter/main.py
    networks:
        - system_network
    volumes:
      - ./persistent:/persistent
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=platformreducer
        - NODE_INSTANCE_NAME=platformreducer
        - NODE_ID=105
        - AMOUNT_OF_NODES=1
        - SOURCE=CountByPlatform
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct
        - QUERY=1
        
  selectq2345_0:
    container_name: selectq2345_0
    image: select:latest
    entrypoint: python3 -u /app/system/controllers/select/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        filtergender_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectq2345
        - NODE_INSTANCE_NAME=selectq2345_0
        - NODE_ID=106
        - AMOUNT_OF_NODES=1
        - SOURCE=DataParsed
        - SOURCE_KEY=games
        - SOURCE_TYPE=topic
        - SINK=GamesQ2345
        - SINK_TYPE=direct
        - SELECT=3
        
  filtergender_0:
    container_name: filtergender_0
    image: filtergender:latest
    entrypoint: python3 -u /app/system/controllers/filters/filterGender/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectidnameaction_0:
            condition: service_started
        selectidnameindie_0:
            condition: service_started
        filterdecade_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filtergender
        - NODE_INSTANCE_NAME=filtergender_0
        - NODE_ID=107
        - AMOUNT_OF_NODES=1
        - SOURCE=GamesQ2345
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=GenderGames
        - SINK_TYPE=topic
        - GENDERS=Indie,Action
        
  filterdecade_0:
    container_name: filterdecade_0
    image: filterdecade:latest
    entrypoint: python3 -u /app/system/controllers/filters/filterDecade/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        groupertopaverageplaytime:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterdecade
        - NODE_INSTANCE_NAME=filterdecade_0
        - NODE_ID=108
        - AMOUNT_OF_NODES=1
        - SOURCE=GenderGames
        - SOURCE_KEY=Indie
        - SOURCE_TYPE=topic
        - SINK=DecadeGames
        - SINK_TYPE=direct
        - DECADE=2010
    
  groupertopaverageplaytime:
    container_name: groupertopaverageplaytime
    image: groupertopaverageplaytime:latest
    entrypoint: python3 -u /app/system/controllers/groupers/grouperTopAveragePlaytime/main.py
    networks:
        - system_network
    volumes:
      - ./persistent:/persistent
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=groupertopaverageplaytime
        - NODE_INSTANCE_NAME=groupertopaverageplaytime
        - NODE_ID=109
        - AMOUNT_OF_NODES=1
        - SOURCE=DecadeGames
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct
        - TOP_SIZE=10
        - QUERY=2
        
  selectidnameindie_0:
    container_name: selectidnameindie_0
    image: select:latest
    entrypoint: python3 -u /app/system/controllers/select/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectidnameindie
        - NODE_INSTANCE_NAME=selectidnameindie_0
        - NODE_ID=110
        - AMOUNT_OF_NODES=1
        - SOURCE=GenderGames
        - SOURCE_KEY=Indie
        - SOURCE_TYPE=topic
        - SINK=MonitorQ3
        - SINK_TYPE=direct
        - SELECT=6
        
  filterscorepositive_0:
    container_name: filterscorepositive_0
    image: filterscore:latest
    entrypoint: python3 -u /app/system/controllers/filters/filterScore/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterscorepositive
        - NODE_INSTANCE_NAME=filterscorepositive_0
        - NODE_ID=111
        - AMOUNT_OF_NODES=1
        - SOURCE=DataParsed
        - SOURCE_KEY=reviews
        - SOURCE_TYPE=topic
        - SINK=ReviewsPositives
        - SINK_TYPE=direct
        - SCORE_WANTED=1
    
  monitorstorageq3:
    container_name: monitorstorageq3
    image: monitorstorageq3:latest
    entrypoint: python3 -u /app/system/controllers/storages/monitorStorageQ3/main.py
    networks:
        - system_network
    volumes:
      - ./persistent:/persistent
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        groupertopreviewspositiveindie:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorstorageq3
        - NODE_INSTANCE_NAME=monitorstorageq3
        - NODE_ID=112
        - AMOUNT_OF_NODES=1
        - SOURCE=ReviewsPositives,MonitorQ3
        - SOURCE_KEY=default,default
        - SOURCE_TYPE=direct,direct
        - SINK=IndieGamesReviewed
        - SINK_TYPE=direct
    
  groupertopreviewspositiveindie:
    container_name: groupertopreviewspositiveindie
    image: groupertopreviewspositiveindie:latest
    entrypoint: python3 -u /app/system/controllers/groupers/grouperTopReviewsPositiveIndie/main.py
    networks:
        - system_network
    volumes:
      - ./persistent:/persistent
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=groupertopreviewspositiveindie
        - NODE_INSTANCE_NAME=groupertopreviewspositiveindie
        - NODE_ID=113
        - AMOUNT_OF_NODES=1
        - SOURCE=IndieGamesReviewed
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct
        - TOP_SIZE=5
        - QUERY=3
        
  selectidnameaction_0:
    container_name: selectidnameaction_0
    image: select:latest
    entrypoint: python3 -u /app/system/controllers/select/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorjoinerq4:
            condition: service_started
        monitorstorageq5:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectidnameaction
        - NODE_INSTANCE_NAME=selectidnameaction_0
        - NODE_ID=114
        - AMOUNT_OF_NODES=1
        - SOURCE=GenderGames
        - SOURCE_KEY=Action
        - SOURCE_TYPE=topic
        - SINK=MonitorQ45
        - SINK_TYPE=fanout
        - SELECT=6
        
  filterscorenegative_0:
    container_name: filterscorenegative_0
    image: filterscore:latest
    entrypoint: python3 -u /app/system/controllers/filters/filterScore/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorjoinerq4:
            condition: service_started
        monitorstorageq5:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterscorenegative
        - NODE_INSTANCE_NAME=filterscorenegative_0
        - NODE_ID=115
        - AMOUNT_OF_NODES=1
        - SOURCE=DataParsed
        - SOURCE_KEY=reviews
        - SOURCE_TYPE=topic
        - SINK=ReviewsNegatives
        - SINK_TYPE=fanout
        - SCORE_WANTED=-1
    
  monitorjoinerq4:
    container_name: monitorjoinerq4
    image: monitorjoinerq4:latest
    entrypoint: python3 -u /app/system/controllers/joiners/monitorJoinerQ4/main.py
    networks:
        - system_network
    volumes:
      - ./persistent:/persistent
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        filterreviewenglish_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorjoinerq4
        - NODE_INSTANCE_NAME=monitorjoinerq4
        - NODE_ID=116
        - AMOUNT_OF_NODES=1
        - SOURCE=ReviewsNegatives,MonitorQ45
        - SOURCE_KEY=default,default
        - SOURCE_TYPE=fanout,fanout
        - SINK=ActionGamesReviewed
        - SINK_TYPE=direct
        
  filterreviewenglish_0:
    container_name: filterreviewenglish_0
    image: filterreviewenglish:latest
    entrypoint: python3 -u /app/system/controllers/filters/filterReviewEnglish/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq4:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterreviewenglish
        - NODE_INSTANCE_NAME=filterreviewenglish_0
        - NODE_ID=117
        - AMOUNT_OF_NODES=1
        - SOURCE=ActionGamesReviewed
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=ActionGamesEnglishReviews
        - SINK_TYPE=direct
    
  monitorstorageq4:
    container_name: monitorstorageq4
    image: monitorstorageq4:latest
    entrypoint: python3 -u /app/system/controllers/storages/monitorStorageQ4/main.py
    networks:
        - system_network
    volumes:
      - ./persistent:/persistent
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorstorageq4
        - NODE_INSTANCE_NAME=monitorstorageq4
        - NODE_ID=118
        - AMOUNT_OF_NODES=1
        - SOURCE=ActionGamesEnglishReviews
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct
        - AMOUNT_NEEDED=5000
        - QUERY=4
    
  monitorstorageq5:
    container_name: monitorstorageq5
    image: monitorstorageq5:latest
    entrypoint: python3 -u /app/system/controllers/storages/monitorStorageQ5/main.py
    networks:
        - system_network
    volumes:
      - ./persistent:/persistent
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorstorageq5
        - NODE_INSTANCE_NAME=monitorstorageq5
        - NODE_ID=119
        - AMOUNT_OF_NODES=1
        - SOURCE=ReviewsNegatives,MonitorQ45
        - SOURCE_KEY=default,default
        - SOURCE_TYPE=fanout,fanout
        - SINK=Output
        - SINK_TYPE=direct
        - PERCENTILE=0.9
        - QUERY=5

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
