
version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Puerto para conexión con RabbitMQ
      - "15672:15672"  # Puerto para la interfaz de administración
    networks:
      - testing_net

  Input:
    container_name: Input
    build:
      context: ./Input
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  Output:
    container_name: Output
    build:
      context: ./Output
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  PlatformReducer:
    container_name: PlatformReducer
    build:
      context: ./PlatformReducer
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  SorterTop10AveragePlayTime:
    container_name: SorterTop10AveragePlayTime
    build:
      context: ./SorterTop10AveragePlayTime
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  GrouperTop5ReviewsPosIndie:
    container_name: GrouperTop5ReviewsPosIndie
    build:
      context: ./GrouperTop5ReviewsPosIndie
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  GameIn90thPercentile:
    container_name: GameIn90thPercentile
    build:
      context: ./GameIn90thPercentile
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  FilterBasic_1:
    container_name: FilterBasic_1
    build:
      context: ./FilterBasic  # Carpeta donde está el Dockerfile de FilterBasic
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  SelectQ1_1:
    container_name: SelectQ1_1
    build:
      context: ./SelectQ1  # Carpeta donde está el Dockerfile de SelectQ1
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  PlatformCounter_1:
    container_name: PlatformCounter_1
    build:
      context: ./PlatformCounter  # Carpeta donde está el Dockerfile de PlatformCounter
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  SelectQ2345_1:
    container_name: SelectQ2345_1
    build:
      context: ./SelectQ2345  # Carpeta donde está el Dockerfile de SelectQ2345
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  FilterGender_1:
    container_name: FilterGender_1
    build:
      context: ./FilterGender  # Carpeta donde está el Dockerfile de FilterGender
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  FilterDecade2010_1:
    container_name: FilterDecade2010_1
    build:
      context: ./FilterDecade2010  # Carpeta donde está el Dockerfile de FilterDecade2010
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  SelectIDName_1:
    container_name: SelectIDName_1
    build:
      context: ./SelectIDName  # Carpeta donde está el Dockerfile de SelectIDName
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  SelectQ345_1:
    container_name: SelectQ345_1
    build:
      context: ./SelectQ345  # Carpeta donde está el Dockerfile de SelectQ345
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  FilterScorePositive_1:
    container_name: FilterScorePositive_1
    build:
      context: ./FilterScorePositive  # Carpeta donde está el Dockerfile de FilterScorePositive
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  FilterReviewEnglish_1:
    container_name: FilterReviewEnglish_1
    build:
      context: ./FilterReviewEnglish  # Carpeta donde está el Dockerfile de FilterReviewEnglish
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  FilterScore50kPositives_1:
    container_name: FilterScore50kPositives_1
    build:
      context: ./FilterScore50kPositives  # Carpeta donde está el Dockerfile de FilterScore50kPositives
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  FilterScoreNegative_1:
    container_name: FilterScoreNegative_1
    build:
      context: ./FilterScoreNegative  # Carpeta donde está el Dockerfile de FilterScoreNegative
      dockerfile: Dockerfile         # Nombre del Dockerfile (opcional si es el predeterminado)
    networks:
      - testing_net
    depends_on:
      - rabbitmq

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
