
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /app/client/main.py
    volumes:
      - ./data/games.csv:/data/games.csv
      - ./data/dataset.csv:/data/dataset.csv
      - ./data/responses:/data/responses
    environment:
      - PERCENT_OF_FILE_FOR_USE_BY_EXECUTION=0.1,0.2,0.3
      - NODE_ID=1
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - HOSTNAME=gateway
      - SEND_REVIEWS=0
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/system/controllers/gateway/main.py
    networks:
        - system_network
    restart: on-failure
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=gateway
        - NODE_ID=1
        - SOURCE=Output
        - SINK=DataRaw
        - AMOUNT_OF_QUERIES=1
    depends_on:
      rabbitmq:
        condition: service_healthy
      filterbasic_0:
        condition: service_started

  filterbasic_0:
    container_name: filterbasic_0
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectq1_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterbasic
        - NODE_ID=0
        - AMOUNT_OF_NODES=1
        - SOURCE=DataRaw
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=DataParsed
        - SINK_TYPE=topic

  selectq1_0:
    container_name: selectq1_0
    image: select:latest
    entrypoint: python3 /app/system/controllers/select/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        platformcounter_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectq1
        - NODE_ID=0
        - AMOUNT_OF_NODES=1
        - SOURCE=DataParsed
        - SOURCE_KEY=games
        - SOURCE_TYPE=topic
        - SINK=GamesPlatform
        - SINK_TYPE=direct
        - SELECT=2

  platformcounter_0:
    container_name: platformcounter_0
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        platformreducer:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=platformcounter
        - NODE_ID=0
        - AMOUNT_OF_NODES=1
        - SOURCE=GamesPlatform
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=CountByPlatform
        - SINK_TYPE=direct

  platformreducer:
    container_name: platformreducer
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=platformreducer
        - NODE_ID=0
        - AMOUNT_OF_NODES=1
        - SOURCE=CountByPlatform
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
