
version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"  # Puerto para conexion con RabbitMQ
      - "15672:15672"  # Puerto para la interfaz de administracion
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"] # -f hace q curl falle silenciosamente si la web no funciona
      interval: 10s #verifica salud de rabbit each 10 s
      timeout: 5s # si rabbit no responde en 5s falla 
      retries: 10 # luego de 10 intentos => no es saludable

  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ./data/games/games.csv:/data/games.csv
      - ./data/reviews/dataset.csv:/data/dataset.csv
    environment:
      - NODE_ID= 1
      - CLI_LOG_LEVEL= INFO
      - PYTHONPATH= /app  # le decimos a python que incluya /app para buscar paquetes asi podra encontrar el paquete client (/app/client). 
    entrypoint: python3 /app/client/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      input:
        condition: service_started  # Puede esperar simplemente a que el sistema se haya iniciado    

  input:
    container_name: input
    build:
      context: .
      dockerfile: system/controllers/input/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: "input"
      NODE_ID: 2
      SOURCE: ""
      SINK: "input_exchange"
      LOGGING_LEVEL: INFO
      PYTHONPATH: /app

  output:
    container_name: output
    build:
      context: .
      dockerfile: system/controllers/output/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: "output"
      NODE_ID: 3
      SOURCE: "response_exchange"
      SINK: ""

  platformreducer:
    container_name: platformreducer
    build:
      context: .
      dockerfile: system/controllers/groupers/platformCounter/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: "platformreducer"
      NODE_ID: 4
      SOURCE: "platformcounter_exchange"
      SINK: "response_exchange"

  # sortertop10averageplaytime:
  #   container_name: sortertop10averageplaytime
  #   build:
  #     context: .
  #     dockerfile: sortertop10averageplaytime/Dockerfile
  #   networks:
  #     - system_network
  #   depends_on:
  #     - rabbitmq

  groupertopreviewspositiveindie:
    container_name: groupertopreviewspositiveindie
    build:
      context: .
      dockerfile: system/controllers/groupers/grouperTopReviewsPositiveIndie/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: "groupertopreviewspositiveindie"
      NODE_ID: 5
      SOURCE: ""
      SINK: ""
      

  # gamein90thpercentile:
  #   container_name: gamein90thpercentile
  #   build:
  #     context: .
  #     dockerfile: system/controllers/gamein90thpercentile/Dockerfile
  #   networks:
  #     - system_network
  #   depends_on:
  #     - rabbitmq

  filterbasic_1:
    container_name: filterbasic_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterBasic/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: filterbasic_1
      NODE_ID: 6
      SOURCE: input_exchange
      SINK: filterbasic_exchange

  platformcounter_1:
    container_name: platformcounter_1
    build:
      context: .
      dockerfile: system/controllers/groupers/platformCounter/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: platformcounter_1
      NODE_ID: 6
      SOURCE: selectq1_exchange
      SINK: platformcounter_exchange

  selectq2345_1:
    container_name: selectq2345_1
    build:
      context: .
      dockerfile: system/controllers/select/selectQ2345/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: selectq2345_1
      NODE_ID: 6
      SOURCE: filterbasic_exchange
      SINK: selectq2345_exchange

  filtergender_1:
    container_name: filtergender_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterGender/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: filtergender_1
      NODE_ID: 6
      SOURCE: selectq2345_exchange
      SINK: filtergender_exchange

  filterdecade_1:
    container_name: filterdecade_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterDecade/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: filterdecade_1
      NODE_ID: 6
      SOURCE: filtergender_exchange
      SINK: filterdecade_exchange

  selectidname_1:
    container_name: selectidname_1
    build:
      context: .
      dockerfile: system/controllers/select/selectIDName/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: selectidname_1
      NODE_ID: 6
      SOURCE: filtergender_exchange
      SINK: selectidname_exchange

  selectq345_1:
    container_name: selectq345_1
    build:
      context: .
      dockerfile: system/controllers/select/selectQ345/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: selectq345_1
      NODE_ID: 6
      SOURCE: filterbasic_exchange
      SINK: selectq345_exchange

  filterscorepositive_1:
    container_name: filterscorepositive_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterScorePositive/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: filterscorepositive_1
      NODE_ID: 6
      SOURCE: ERROR
      SINK: filterscorepositive_exchange

  filterreviewenglish_1:
    container_name: filterreviewenglish_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterReviewEnglish/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: filterreviewenglish_1
      NODE_ID: 6
      SOURCE: selectq345_exchange
      SINK: filterreviewenglish_exchange

  filterscorexpositives_1:
    container_name: filterscorexpositives_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterScoreXPositives/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: filterscorexpositives_1
      NODE_ID: 6
      SOURCE: ERROR
      SINK: filterscorexpositives_exchange

  filterscorenegative_1:
    container_name: filterscorenegative_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterScoreNegative/Dockerfile
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_NAME: filterscorenegative_1
      NODE_ID: 6
      SOURCE: selectq345_exchange
      SINK: filterscorenegative_exchange

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
