
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /app/client/main.py
    volumes:
      - ./data/games.csv:/data/games.csv
      - ./data/dataset.csv:/data/dataset.csv
    environment:
      - NODE_ID=1
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - HOSTNAME=gateway
      - SEND_REVIEWS=1
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/system/controllers/gateway/main.py
    networks:
        - system_network
    restart: on-failure
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=gateway
        - NODE_ID=1
        - SOURCE=Output
        - SINK=DataRaw
        - AMOUNT_OF_QUERIES=1
    depends_on:
      rabbitmq:
        condition: service_healthy
      filterbasic_0:
        condition: service_started
      filterbasic_1:
        condition: service_started
      filterbasic_2:
        condition: service_started

  filterbasic_0:
    container_name: filterbasic_0
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectq2345_0:
            condition: service_started
        selectq2345_1:
            condition: service_started
        selectq2345_2:
            condition: service_started
        filterscorepositive_0:
            condition: service_started
        filterscorepositive_1:
            condition: service_started
        filterscorepositive_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterbasic
        - NODE_ID=0
        - AMOUNT_OF_NODES=3
        - SOURCE=DataRaw
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=DataParsed
        - SINK_TYPE=topic

  filterbasic_1:
    container_name: filterbasic_1
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectq2345_0:
            condition: service_started
        selectq2345_1:
            condition: service_started
        selectq2345_2:
            condition: service_started
        filterscorepositive_0:
            condition: service_started
        filterscorepositive_1:
            condition: service_started
        filterscorepositive_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterbasic
        - NODE_ID=1
        - AMOUNT_OF_NODES=3
        - SOURCE=DataRaw
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=DataParsed
        - SINK_TYPE=topic

  filterbasic_2:
    container_name: filterbasic_2
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectq2345_0:
            condition: service_started
        selectq2345_1:
            condition: service_started
        selectq2345_2:
            condition: service_started
        filterscorepositive_0:
            condition: service_started
        filterscorepositive_1:
            condition: service_started
        filterscorepositive_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterbasic
        - NODE_ID=2
        - AMOUNT_OF_NODES=3
        - SOURCE=DataRaw
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=DataParsed
        - SINK_TYPE=topic

  selectq2345_0:
    container_name: selectq2345_0
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        filtergender_0:
            condition: service_started
        filtergender_1:
            condition: service_started
        filtergender_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectq2345
        - NODE_ID=0
        - AMOUNT_OF_NODES=3
        - SOURCE=DataParsed
        - SOURCE_KEY=games
        - SOURCE_TYPE=topic
        - SINK=GamesQ2345
        - SINK_TYPE=direct

  selectq2345_1:
    container_name: selectq2345_1
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        filtergender_0:
            condition: service_started
        filtergender_1:
            condition: service_started
        filtergender_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectq2345
        - NODE_ID=1
        - AMOUNT_OF_NODES=3
        - SOURCE=DataParsed
        - SOURCE_KEY=games
        - SOURCE_TYPE=topic
        - SINK=GamesQ2345
        - SINK_TYPE=direct

  selectq2345_2:
    container_name: selectq2345_2
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        filtergender_0:
            condition: service_started
        filtergender_1:
            condition: service_started
        filtergender_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectq2345
        - NODE_ID=2
        - AMOUNT_OF_NODES=3
        - SOURCE=DataParsed
        - SOURCE_KEY=games
        - SOURCE_TYPE=topic
        - SINK=GamesQ2345
        - SINK_TYPE=direct

  filtergender_0:
    container_name: filtergender_0
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectidnameindie_0:
            condition: service_started
        selectidnameindie_1:
            condition: service_started
        selectidnameindie_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filtergender
        - NODE_ID=0
        - AMOUNT_OF_NODES=3
        - SOURCE=GamesQ2345
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=GenderGames
        - SINK_TYPE=topic
        - GENDERS=Indie,Action

  filtergender_1:
    container_name: filtergender_1
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectidnameindie_0:
            condition: service_started
        selectidnameindie_1:
            condition: service_started
        selectidnameindie_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filtergender
        - NODE_ID=1
        - AMOUNT_OF_NODES=3
        - SOURCE=GamesQ2345
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=GenderGames
        - SINK_TYPE=topic
        - GENDERS=Indie,Action

  filtergender_2:
    container_name: filtergender_2
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectidnameindie_0:
            condition: service_started
        selectidnameindie_1:
            condition: service_started
        selectidnameindie_2:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filtergender
        - NODE_ID=2
        - AMOUNT_OF_NODES=3
        - SOURCE=GamesQ2345
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=GenderGames
        - SINK_TYPE=topic
        - GENDERS=Indie,Action

  selectidnameindie_0:
    container_name: selectidnameindie_0
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectidnameindie
        - NODE_ID=0
        - AMOUNT_OF_NODES=3
        - SOURCE=GenderGames
        - SOURCE_KEY=Indie
        - SOURCE_TYPE=topic
        - SINK=MonitorQ3
        - SINK_TYPE=direct

  selectidnameindie_1:
    container_name: selectidnameindie_1
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectidnameindie
        - NODE_ID=1
        - AMOUNT_OF_NODES=3
        - SOURCE=GenderGames
        - SOURCE_KEY=Indie
        - SOURCE_TYPE=topic
        - SINK=MonitorQ3
        - SINK_TYPE=direct

  selectidnameindie_2:
    container_name: selectidnameindie_2
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectidnameindie
        - NODE_ID=2
        - AMOUNT_OF_NODES=3
        - SOURCE=GenderGames
        - SOURCE_KEY=Indie
        - SOURCE_TYPE=topic
        - SINK=MonitorQ3
        - SINK_TYPE=direct

  filterscorepositive_0:
    container_name: filterscorepositive_0
    image: filterscore:latest
    entrypoint: python3 /app/system/controllers/filters/filterScore/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterscorepositive
        - NODE_ID=0
        - AMOUNT_OF_NODES=3
        - SOURCE=DataParsed
        - SOURCE_KEY=reviews
        - SOURCE_TYPE=topic
        - SINK=ReviewsPositives
        - SINK_TYPE=direct
        - SCORE_WANTED=1

  filterscorepositive_1:
    container_name: filterscorepositive_1
    image: filterscore:latest
    entrypoint: python3 /app/system/controllers/filters/filterScore/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterscorepositive
        - NODE_ID=1
        - AMOUNT_OF_NODES=3
        - SOURCE=DataParsed
        - SOURCE_KEY=reviews
        - SOURCE_TYPE=topic
        - SINK=ReviewsPositives
        - SINK_TYPE=direct
        - SCORE_WANTED=1

  filterscorepositive_2:
    container_name: filterscorepositive_2
    image: filterscore:latest
    entrypoint: python3 /app/system/controllers/filters/filterScore/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterscorepositive
        - NODE_ID=2
        - AMOUNT_OF_NODES=3
        - SOURCE=DataParsed
        - SOURCE_KEY=reviews
        - SOURCE_TYPE=topic
        - SINK=ReviewsPositives
        - SINK_TYPE=direct
        - SCORE_WANTED=1

  monitorstorageq3:
    container_name: monitorstorageq3
    image: monitorstorageq3:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ3/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        groupertopreviewspositiveindie:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorstorageq3
        - NODE_ID=0
        - AMOUNT_OF_NODES=1
        - SOURCE=ReviewsPositives,MonitorQ3
        - SOURCE_KEY=default,default
        - SOURCE_TYPE=direct,direct
        - SINK=IndieGamesReviewed
        - SINK_TYPE=direct

  groupertopreviewspositiveindie:
    container_name: groupertopreviewspositiveindie
    image: groupertopreviewspositiveindie:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopReviewsPositiveIndie/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=groupertopreviewspositiveindie
        - NODE_ID=0
        - AMOUNT_OF_NODES=1
        - SOURCE=IndieGamesReviewed
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct
        - TOP_SIZE=5

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
