
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    

  medic_0:
    container_name: medic_0
    image: leader:latest
    entrypoint: python3 -u /app/system/leader/main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_NAME=medic_0  
      - NODE_ID=500
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    
  medic_1:
    container_name: medic_1
    image: leader:latest
    entrypoint: python3 -u /app/system/leader/main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_NAME=medic_1  
      - NODE_ID=501
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic_0:
        condition: service_started
    
  medic_2:
    container_name: medic_2
    image: leader:latest
    entrypoint: python3 -u /app/system/leader/main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_NAME=medic_2  
      - NODE_ID=502
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic_1:
        condition: service_started
    
  medic_3:
    container_name: medic_3
    image: leader:latest
    entrypoint: python3 -u /app/system/leader/main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_NAME=medic_3  
      - NODE_ID=503
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic_2:
        condition: service_started
    
  gateway:
    image: "nodetoy:latest"
    container_name: gateway
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=gateway
      - NODE_ID=101
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  filterbasic_0:
    image: "nodetoy:latest"
    container_name: filterbasic_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=filterbasic_0
      - NODE_ID=102
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  selectq1_0:
    image: "nodetoy:latest"
    container_name: selectq1_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=selectq1_0
      - NODE_ID=103
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  platformcounter_0:
    image: "nodetoy:latest"
    container_name: platformcounter_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=platformcounter_0
      - NODE_ID=104
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  platformreducer:
    image: "nodetoy:latest"
    container_name: platformreducer
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=platformreducer
      - NODE_ID=105
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  selectq2345_0:
    image: "nodetoy:latest"
    container_name: selectq2345_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=selectq2345_0
      - NODE_ID=106
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  filtergender_0:
    image: "nodetoy:latest"
    container_name: filtergender_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=filtergender_0
      - NODE_ID=107
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  filterdecade_0:
    image: "nodetoy:latest"
    container_name: filterdecade_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=filterdecade_0
      - NODE_ID=108
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  groupertopaverageplaytime:
    image: "nodetoy:latest"
    container_name: groupertopaverageplaytime
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=groupertopaverageplaytime
      - NODE_ID=109
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  selectidnameindie_0:
    image: "nodetoy:latest"
    container_name: selectidnameindie_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=selectidnameindie_0
      - NODE_ID=110
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  filterscorepositive_0:
    image: "nodetoy:latest"
    container_name: filterscorepositive_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=filterscorepositive_0
      - NODE_ID=111
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  monitorstorageq3:
    image: "nodetoy:latest"
    container_name: monitorstorageq3
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=monitorstorageq3
      - NODE_ID=112
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  groupertopreviewspositiveindie:
    image: "nodetoy:latest"
    container_name: groupertopreviewspositiveindie
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=groupertopreviewspositiveindie
      - NODE_ID=113
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  selectidnameaction_0:
    image: "nodetoy:latest"
    container_name: selectidnameaction_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=selectidnameaction_0
      - NODE_ID=114
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  filterscorenegative_0:
    image: "nodetoy:latest"
    container_name: filterscorenegative_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=filterscorenegative_0
      - NODE_ID=115
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  monitorjoinerq4:
    image: "nodetoy:latest"
    container_name: monitorjoinerq4
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=monitorjoinerq4
      - NODE_ID=116
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  filterreviewenglish_0:
    image: "nodetoy:latest"
    container_name: filterreviewenglish_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=filterreviewenglish_0
      - NODE_ID=117
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  monitorstorageq4:
    image: "nodetoy:latest"
    container_name: monitorstorageq4
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=monitorstorageq4
      - NODE_ID=118
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  monitorstorageq5:
    image: "nodetoy:latest"
    container_name: monitorstorageq5
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=monitorstorageq5
      - NODE_ID=119
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network
networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
