version: '3.8'
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"  # Puerto para conexion con RabbitMQ
      - "15672:15672"  # Puerto para la interfaz de administracion
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"] # -f hace q curl falle silenciosamente si la web no funciona
      interval: 10s #verifica salud de rabbit each 10 s
      timeout: 5s # si rabbit no responde en 5s falla 
      retries: 10 # luego de 10 intentos => no es saludable

  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ./data/games/games.csv:/data/games.csv
      - ./data/reviews/dataset.csv:/data/dataset.csv
      - ./results:/results
    environment:
      - NODE_ID=1
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - HOSTNAME=gateway
    entrypoint: python3 /app/client/main.py
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/system/controllers/gateway/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  filterbasic_1:
    container_name: filterbasic_1
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=3
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  filterbasic_2:
    container_name: filterbasic_2
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=4
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  filterbasic_3:
    container_name: filterbasic_3
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=5
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  selectQ1_1:
    container_name: selectQ1_1
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=6
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  selectQ1_2:
    container_name: selectQ1_2
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=7
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable        

  selectQ1_3:
    container_name: selectQ1_3
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=8
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable        

  platformcounter_1:
    container_name: platformcounter_1
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=platformcounter_1
      - NODE_ID=9
      - TOTAL_NODES=2
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  platformcounter_2:
    container_name: platformcounter_2
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=platformcounter_1
      - NODE_ID=10
      - TOTAL_NODES=2
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

#Es una unica instancia el reducer
  platformreducer:
    container_name: platformreducer
    image: platformreducer:latest
    entrypoint: python3 /app/system/controllers/reducers/platformReducer/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME="platformreducer"
      - NODE_ID=11
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy


  selectQ2345_1:
    container_name: selectq2345_1
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectq2345_1
      - NODE_ID=12
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectQ2345_2:
    container_name: selectq2345_2
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectq2345_2
      - NODE_ID=13
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectQ2345_3:
    container_name: selectq2345_3
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectq2345_3
      - NODE_ID=14
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy        

  filterGender_1:
    container_name: filtergender_1
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filtergender_1
      - NODE_ID=15
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy        

  filterGender_2:
    container_name: filtergender_2
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filtergender_2
      - NODE_ID=16
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy    
  
  filterGender_3:
    container_name: filtergender_3
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filtergender_3
      - NODE_ID=17
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterDecade_1:
    container_name: filterdecade_1
    image: filterdecade:latest
    entrypoint: python3 /app/system/controllers/filters/filterDecade/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterdecade_1
      - NODE_ID=18
      - TOTAL_NODES=2
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterDecade_2:
    container_name: filterdecade_2
    image: filterdecade:latest
    entrypoint: python3 /app/system/controllers/filters/filterDecade/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterdecade_2
      - NODE_ID=19
      - TOTAL_NODES=2
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  grouperTopAvgPlaytime:
    container_name: groupertopavgplaytime
    image: groupertopavgplaytime:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopAvgPlaytime/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=groupertopavgplaytime
      - NODE_ID=20
      - TOTAL_NODES=1
      - TOP_SIZE=10
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterScorePositive_1:
    container_name: filterscorepositive_1
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterscorepositive_1
      - NODE_ID=21
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterScorePositive_2:
    container_name: filterscorepositive_2
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterscorepositive_2
      - NODE_ID=22
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterScorePositive_3:
    container_name: filterscorepositive_3
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterscorepositive_3
      - NODE_ID=23
      - TOTAL_NODES=3
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy


  # sortertop10averageplaytime:
  #   container_name: sortertop10averageplaytime
  #   build:
  #     context: .
  #     dockerfile: sortertop10averageplaytime/Dockerfile
  #   networks:
  #     - system_network
  #   depends_on:
  #     - rabbitmq
#
#  groupertopreviewspositiveindie:
#    container_name: groupertopreviewspositiveindie
#    build:
#      context: .
#      dockerfile: system/controllers/groupers/grouperTopReviewsPositiveIndie/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="groupertopreviewspositiveindie"
#      - NODE_ID=5
#      - SOURCE=""
#      - SINK=""
#      - LOGGING_LEVEL=INFO
#  # gamein90thpercentile:
  #   container_name: gamein90thpercentile
  #   build:
  #     context: .
  #     dockerfile: system/controllers/gamein90thpercentile/Dockerfile
  #   networks:
  #     - system_network
  #   depends_on:
  #     - rabbitmq





#  filterdecade_1:
#    container_name: filterdecade_1
#    build:
#      context: .
#      dockerfile: system/controllers/filters/filterDecade/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="filterdecade_1"
#      - NODE_ID=6
#      - SOURCE=GamesIndieQ2
#      - SINK=
#      - LOGGING_LEVEL=INFO
#
#  selectidnameindie_1:
#    container_name: selectidnameindie_1
#    build:
#      context: .
#      dockerfile: system/controllers/select/selectIDNameIndie/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="selectidnameindie_1"
#      - NODE_ID=6
#      - SOURCE=GamesIndieQ3
#      - SINK=
#      - LOGGING_LEVEL=INFO
#
#  selectidnameaction_1:
#    container_name: selectidnameaction_1
#    build:
#      context: .
#      dockerfile: system/controllers/select/selectIDNameAction/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="selectidnameaction_1"
#      - NODE_ID=6
#      - SOURCE=GamesActionQ45
#      - SINK=
#      - LOGGING_LEVEL=INFO
#
#  selectq345_1:
#    container_name: selectq345_1
#    build:
#      context: .
#      dockerfile: system/controllers/select/selectQ345/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="selectq345_1"
#      - NODE_ID=6
#      - SOURCE=DataParsed
#      - SINK=
#      - LOGGING_LEVEL=INFO
#
#  filterscorepositive_1:
#    container_name: filterscorepositive_1
#    build:
#      context: .
#      dockerfile: system/controllers/filters/filterScorePositive/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="filterscorepositive_1"
#      - NODE_ID=6
#      - SOURCE=ERROR
#      - SINK=ERROR
#      - LOGGING_LEVEL=INFO
#
#  filterreviewenglish_1:
#    container_name: filterreviewenglish_1
#    build:
#      context: .
#      dockerfile: system/controllers/filters/filterReviewEnglish/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="filterreviewenglish_1"
#      - NODE_ID=6
#      - SOURCE=GamesActionPositives
#      - SINK=
#      - LOGGING_LEVEL=INFO
#
#  filterscorexpositives_1:
#    container_name: filterscorexpositives_1
#    build:
#      context: .
#      dockerfile: system/controllers/filters/filterScoreXPositives/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="filterscorexpositives_1"
#      - NODE_ID=6
#      - SOURCE=ERROR
#      - SINK=ERROR
#      - LOGGING_LEVEL=INFO
#
#  filterscorenegative_1:
#    container_name: filterscorenegative_1
#    build:
#      context: .
#      dockerfile: system/controllers/filters/filterScoreNegative/Dockerfile
#    networks:
#      - system_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      - NODE_NAME="filterscorenegative_1"
#      - NODE_ID=6
#      - SOURCE=ReviewsRaw
#      - SINK=
#      - LOGGING_LEVEL=INFO

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
