
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /app/client/main.py
    volumes:
      - ./data/games.csv:/data/games.csv
      - ./data/dataset.csv:/data/dataset.csv
    environment:
      - NODE_ID=1
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - HOSTNAME=gateway
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/system/controllers/gateway/main.py
    networks:
        - system_network
    restart: on-failure
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=gateway
        - NODE_ID=1
        - SOURCE=Output
        - SINK=DataParsed
        - SINK_TYPE=topic
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectq1_0:
    container_name: selectq1_0
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        platformcounter_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectq1
        - NODE_ID=0
        - SOURCE=DataParsed
        - SOURCE_KEY=games
        - SOURCE_TYPE=topic
        - SINK=GamesPlatform
        - SINK_TYPE=direct

  platformcounter_0:
    container_name: platformcounter_0
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        platformreducer:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=platformcounter
        - NODE_ID=0
        - SOURCE=GamesPlatform
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=CountByPlatform
        - SINK_TYPE=direct

  platformreducer:
    container_name: platformreducer
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=platformreducer
        - NODE_ID=0
        - SOURCE=CountByPlatform
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct

  selectq2345_0:
    container_name: selectq2345_0
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        filtergender_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectq2345
        - NODE_ID=0
        - SOURCE=DataParsed
        - SOURCE_KEY=games
        - SOURCE_TYPE=topic
        - SINK=GamesQ2345
        - SINK_TYPE=direct

  filtergender_0:
    container_name: filtergender_0
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        selectidnameaction_0:
            condition: service_started
        selectidnameindie_0:
            condition: service_started
        filterdecade_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filtergender
        - NODE_ID=0
        - SOURCE=GamesQ2345
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=GenderGames
        - SINK_TYPE=topic
        - GENDERS=Indie,Action

  filterdecade_0:
    container_name: filterdecade_0
    image: filterdecade:latest
    entrypoint: python3 /app/system/controllers/filters/filterDecade/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        groupertopaverageplaytime:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterdecade
        - NODE_ID=0
        - SOURCE=GenderGames
        - SOURCE_KEY=Indie
        - SOURCE_TYPE=topic
        - SINK=DecadeGames
        - SINK_TYPE=direct
        - DECADE=2010

  groupertopaverageplaytime:
    container_name: groupertopaverageplaytime
    image: groupertopaverageplaytime:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopAveragePlaytime/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=groupertopaverageplaytime
        - NODE_ID=0
        - SOURCE=DecadeGames
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct
        - TOP_SIZE=10

  selectidnameindie_0:
    container_name: selectidnameindie_0
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectidnameindie
        - NODE_ID=0
        - SOURCE=GenderGames
        - SOURCE_KEY=Indie
        - SOURCE_TYPE=topic
        - SINK=MonitorQ3
        - SINK_TYPE=direct

  filterscorepositive_0:
    container_name: filterscorepositive_0
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq3:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterscorepositive
        - NODE_ID=0
        - SOURCE=DataParsed
        - SOURCE_KEY=reviews
        - SOURCE_TYPE=topic
        - SINK=ReviewsPositives
        - SINK_TYPE=direct

  monitorstorageq3:
    container_name: monitorstorageq3
    image: monitorstorageq3:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ3/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        groupertopreviewspositiveindie:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorstorageq3
        - NODE_ID=0
        - SOURCE=ReviewsPositives,MonitorQ3
        - SOURCE_KEY=default,default
        - SOURCE_TYPE=direct,direct
        - SINK=IndieGamesReviewed
        - SINK_TYPE=direct

  groupertopreviewspositiveindie:
    container_name: groupertopreviewspositiveindie
    image: groupertopreviewspositiveindie:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopReviewsPositiveIndie/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=groupertopreviewspositiveindie
        - NODE_ID=0
        - SOURCE=IndieGamesReviewed
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct
        - TOP_SIZE=5

  selectidnameaction_0:
    container_name: selectidnameaction_0
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorjoinerq4:
            condition: service_started
        monitorstorageq5:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=selectidnameaction
        - NODE_ID=0
        - SOURCE=GenderGames
        - SOURCE_KEY=Action
        - SOURCE_TYPE=topic
        - SINK=MonitorQ45
        - SINK_TYPE=fanout

  filterscorenegative_0:
    container_name: filterscorenegative_0
    image: filterscorenegative:latest
    entrypoint: python3 /app/system/controllers/filters/filterScoreNegative/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorjoinerq4:
            condition: service_started
        monitorstorageq5:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterscorenegative
        - NODE_ID=0
        - SOURCE=DataParsed
        - SOURCE_KEY=reviews
        - SOURCE_TYPE=topic
        - SINK=ReviewsNegatives
        - SINK_TYPE=fanout

  monitorjoinerq4:
    container_name: monitorjoinerq4
    image: monitorjoinerq4:latest
    entrypoint: python3 /app/system/controllers/joiners/monitorJoinerQ4/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        filterreviewenglish_0:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorjoinerq4
        - NODE_ID=0
        - SOURCE=ReviewsNegatives,MonitorQ45
        - SOURCE_KEY=default,default
        - SOURCE_TYPE=fanout,fanout
        - SINK=ActionGamesReviewed
        - SINK_TYPE=direct

  filterreviewenglish_0:
    container_name: filterreviewenglish_0
    image: filterreviewenglish:latest
    entrypoint: python3 /app/system/controllers/filters/filterReviewEnglish/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
        monitorstorageq4:
            condition: service_started
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=filterreviewenglish
        - NODE_ID=0
        - SOURCE=ActionGamesReviewed
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=ActionGamesEnglishReviews
        - SINK_TYPE=direct

  monitorstorageq4:
    container_name: monitorstorageq4
    image: monitorstorageq4:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ4/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorstorageq4
        - NODE_ID=0
        - SOURCE=ActionGamesEnglishReviews
        - SOURCE_KEY=default
        - SOURCE_TYPE=direct
        - SINK=Output
        - SINK_TYPE=direct
        - AMOUNT_NEEDED=5000

  monitorstorageq5:
    container_name: monitorstorageq5
    image: monitorstorageq5:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ5/main.py
    networks:
        - system_network
    restart: on-failure
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - LOGGING_LEVEL=INFO
        - PYTHONPATH=/app
        - NODE_NAME=monitorstorageq5
        - NODE_ID=0
        - SOURCE=ReviewsNegatives,MonitorQ45
        - SOURCE_KEY=default,default
        - SOURCE_TYPE=fanout,fanout
        - SINK=Output
        - SINK_TYPE=direct
        - PERCENTILE=0.9

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
