services:
  node0:
    image: "leader:latest"
    container_name: node0
    entrypoint: python3 /app/leader/main.py
    environment:
      - NODE_ID=100
      - RING_SIZE=3
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      node1:
        condition: service_started

  node1:
    image: "leader:latest"
    container_name: node1
    entrypoint: python3 /app/leader/main.py
    environment:
      - NODE_ID=101
      - LOGGING_LEVEL=INFO
      - RING_SIZE=3
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      node2:
        condition: service_started

  node2:
    image: "leader:latest"
    container_name: node2
    entrypoint: python3 /app/leader/main.py
    environment:
      - NODE_ID=102
      - LOGGING_LEVEL=INFO
      - RING_SIZE=3
      - PYTHONPATH=/app
    networks:
      - system_network

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
