
version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Puerto para conexion con RabbitMQ
      - "15672:15672"  # Puerto para la interfaz de administracion
    networks:
      - testing_net

  input:
    container_name: input
    build:
      context: .
      dockerfile: system/controllers/input/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  output:
    container_name: output
    build:
      context: .
      dockerfile: system/controllers/output/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  platformreducer:
    container_name: platformreducer
    build:
      context: .
      dockerfile: system/controllers/groupers/platformCounter/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  # sortertop10averageplaytime:
  #   container_name: sortertop10averageplaytime
  #   build:
  #     context: .
  #     dockerfile: sortertop10averageplaytime/Dockerfile
  #   networks:
  #     - testing_net
  #   depends_on:
  #     - rabbitmq

  groupertopreviewspositiveindie:
    container_name: groupertopreviewspositiveindie
    build:
      context: .
      dockerfile: system/controllers/groupers/grouperTopReviewsPositiveIndie/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  # gamein90thpercentile:
  #   container_name: gamein90thpercentile
  #   build:
  #     context: .
  #     dockerfile: system/controllers/gamein90thpercentile/Dockerfile
  #   networks:
  #     - testing_net
  #   depends_on:
  #     - rabbitmq

  filterbasic_1:
    container_name: filterbasic_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterBasic/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  platformcounter_1:
    container_name: platformcounter_1
    build:
      context: .
      dockerfile: system/controllers/groupers/platformCounter/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  selectq2345_1:
    container_name: selectq2345_1
    build:
      context: .
      dockerfile: system/controllers/select/selectQ2345/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filtergender_1:
    container_name: filtergender_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterGender/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterdecade_1:
    container_name: filterdecade_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterDecade/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  selectidname_1:
    container_name: selectidname_1
    build:
      context: .
      dockerfile: system/controllers/select/selectIDName/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  selectq345_1:
    container_name: selectq345_1
    build:
      context: .
      dockerfile: system/controllers/select/selectQ345/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterscorepositive_1:
    container_name: filterscorepositive_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterScorePositive/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterreviewenglish_1:
    container_name: filterreviewenglish_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterReviewEnglish/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterscorexpositives_1:
    container_name: filterscorexpositives_1
    build:
      context: .
      dockerfile: system/controllers/filters/filterScoreXPositives/Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
