services:
  medic_0:
    image: "leader:latest"
    container_name: medic_0
    entrypoint: python3 -u /app/system/leader/main.py
    environment:
      - NODE_NAME=medic
      - NODE_ID=500
      - RING_SIZE=4
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - system_network
    depends_on:
      medic_1:
        condition: service_started

  medic_1:
    image: "leader:latest"
    container_name: medic_1
    entrypoint: python3 -u /app/system/leader/main.py
    environment:
      - NODE_NAME=medic
      - NODE_ID=501
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - system_network
    depends_on:
      medic_2:
        condition: service_started

  medic_2:
    image: "leader:latest"
    container_name: medic_2
    entrypoint: python3 -u /app/system/leader/main.py
    environment:
      - NODE_NAME=medic
      - NODE_ID=502
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - system_network
    depends_on:
      medic_3:
        condition: service_started

  medic_3:
    image: "leader:latest"
    container_name: medic_3
    entrypoint: python3 -u /app/system/leader/main.py
    environment:
      - NODE_NAME=medic
      - NODE_ID=503
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - system_network

  # NODOS DEL SISTEMA ABAJO, changes we need: 
  # 1) node_id creciente siempre. 
  # 2) node_name con el mismo nombre q el nombre del servicio ej: filterbasic_0
  filterbasic_0:
    image: "nodetoy:latest"
    container_name: filterbasic_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=filterbasic_0
      - NODE_ID=100
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  filterbasic_1:
    image: "nodetoy:latest"
    container_name: filterbasic_1
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=filterbasic_1
      - NODE_ID=102
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  nodetoy_0:
    image: "nodetoy:latest"
    container_name: nodetoy_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=nodetoy_0
      - NODE_ID=103
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

  nodetoy_1:
    image: "nodetoy:latest"
    container_name: nodetoy_1
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=nodetoy_1
      - NODE_ID=104
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

networks:
  system_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
