services:
  medic_0:
    image: "leader:latest"
    container_name: medic_0
    entrypoint: python3 -u /app/system/leader/main.py
    environment:
      - NODE_NAME=medic
      - NODE_ID=500
      - RING_SIZE=4
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - system_network
    depends_on:
      medic_1:
        condition: service_started

  medic_1:
    image: "leader:latest"
    container_name: medic_1
    entrypoint: python3 -u /app/system/leader/main.py
    environment:
      - NODE_NAME=medic
      - NODE_ID=501
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - system_network
    depends_on:
      medic_2:
        condition: service_started

  medic_2:
    image: "leader:latest"
    container_name: medic_2
    entrypoint: python3 -u /app/system/leader/main.py
    environment:
      - NODE_NAME=medic
      - NODE_ID=502
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - system_network
    depends_on:
      medic_3:
        condition: service_started

  medic_3:
    image: "leader:latest"
    container_name: medic_3
    entrypoint: python3 -u /app/system/leader/main.py
    environment:
      - NODE_NAME=medic
      - NODE_ID=503
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - system_network

  nodetoy_0:
    image: "nodetoy:latest"
    container_name: nodetoy_0
    entrypoint: python3 -u /app/system/leader/nodeToy/main.py
    environment:
      - NODE_NAME=nodetoy
      - NODE_ID=150
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network

networks:
  system_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
