
version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /app/client/main.py
    volumes:
      - ./data/games/games.csv:/data/games.csv
      - ./data/reviews/dataset.csv:/data/dataset.csv
      - ./results:/results
    environment:
      - NODE_ID=1
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_OF_NODES=1
      - TOP_SIZE=5
      - HOSTNAME=gateway
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/system/controllers/gateway/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME:"gateway"
      - NODE_ID=2
      - SOURCE=""
      - SINK=""
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_OF_NODES=1
      - TOP_SIZE=5

  platformreducer:
    container_name: platformreducer
    image: platformreducer:latest
    entrypoint: python3 /app/system/controllers/reducers/platformReducer/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - NODE_NAME="platformreducer"
      - NODE_ID=3
      - SOURCE="CountByPlatform"
      - SINK={get_sink("platformreducer")}
      - LOGGING_LEVEL=INFO

  groupertopaverageplaytime:
    container_name: groupertopaverageplaytime
    image: groupertopaverageplaytime:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopAveragePlaytime/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - NODE_NAME="groupertopaverageplaytime"
      - NODE_ID=4
      - SOURCE="GamesIndieDecadeQ2"
      - SINK={get_sink("groupertopaverageplaytime")}
      - LOGGING_LEVEL=INFO
      - TOP_SIZE=10

  selectq1_1:
    container_name: selectq1_1
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="selectq1_1"
      - NODE_ID=5
      - SOURCE=DataParsed
      - SINK=GamesPlatform
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  filterbasic_1:
    container_name: filterbasic_1
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="filterbasic_1"
      - NODE_ID=5
      - SOURCE=DataRaw
      - SINK=ERROR
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  platformcounter_1:
    container_name: platformcounter_1
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="platformcounter_1"
      - NODE_ID=5
      - SOURCE=GamesPlatform
      - SINK=countbyplatform
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  selectq2345_1:
    container_name: selectq2345_1
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="selectq2345_1"
      - NODE_ID=5
      - SOURCE=DataParsed
      - SINK=GamesQ2345
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  filtergender_1:
    container_name: filtergender_1
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="filtergender_1"
      - NODE_ID=5
      - SOURCE=GamesQ2345
      - SINK=ERROR
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  filterdecade_1:
    container_name: filterdecade_1
    image: filterdecade:latest
    entrypoint: python3 /app/system/controllers/filters/filterDecade/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="filterdecade_1"
      - NODE_ID=5
      - SOURCE=GamesIndieQ2
      - SINK=GamesIndieDecadeQ2
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  selectidnameindie_1:
    container_name: selectidnameindie_1
    image: selectidnameindie:latest
    entrypoint: python3 /app/system/controllers/select/selectIDNameIndie/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="selectidnameindie_1"
      - NODE_ID=5
      - SOURCE=GamesIndieQ3
      - SINK=GamesIndieQ3Sumarized
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  selectidnameaction_1:
    container_name: selectidnameaction_1
    image: selectidnameaction:latest
    entrypoint: python3 /app/system/controllers/select/selectIDNameAction/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="selectidnameaction_1"
      - NODE_ID=5
      - SOURCE=GamesActionQ45
      - SINK=GamesActionQ45Sumarized
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  selectq345_1:
    container_name: selectq345_1
    image: selectq345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ345/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="selectq345_1"
      - NODE_ID=5
      - SOURCE=DataParsed
      - SINK=ERROR
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  filterscorepositive_1:
    container_name: filterscorepositive_1
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="filterscorepositive_1"
      - NODE_ID=5
      - SOURCE=ERROR
      - SINK=ERROR
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  filterreviewenglish_1:
    container_name: filterreviewenglish_1
    image: filterreviewenglish:latest
    entrypoint: python3 /app/system/controllers/filters/filterReviewEnglish/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="filterreviewenglish_1"
      - NODE_ID=5
      - SOURCE=GamesActionPositives
      - SINK=ReviewsEnglishPositives
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  filterscorexpositives_1:
    container_name: filterscorexpositives_1
    image: filterscorexpositives:latest
    entrypoint: python3 /app/system/controllers/filters/filterScoreXPositives/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="filterscorexpositives_1"
      - NODE_ID=5
      - SOURCE=ERROR
      - SINK=ERROR
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

  filterscorenegative_1:
    container_name: filterscorenegative_1
    image: filterscorenegative:latest
    entrypoint: python3 /app/system/controllers/filters/filterScoreNegative/main.py
    networks:
      - system_network
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_NAME="filterscorenegative_1"
      - NODE_ID=5
      - SOURCE=ReviewsRaw
      - SINK=ReviewsNegatives
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - AMOUNT_NEEDED=5000
      - DECADE=2010
      - AMOUNT_OF_NODES=1
      - GENDERS="Action,Indie"
      - TOP_SIZE=5

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
