services:
  medic0:
    image: "leader:latest"
    container_name: medic0
    entrypoint: python3 /app/system/leader/main.py
    environment:
      - NODE_ID=100
      - RING_SIZE=4
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic1:
        condition: service_started

  medic1:
    image: "leader:latest"
    container_name: medic1
    entrypoint: python3 /app/system/leader/main.py
    environment:
      - NODE_ID=101
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic2:
        condition: service_started

  medic2:
    image: "leader:latest"
    container_name: medic2
    entrypoint: python3 /app/system/leader/main.py
    environment:
      - NODE_ID=102
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network
    depends_on:
      medic3:
        condition: service_started

  medic3:
    image: "leader:latest"
    container_name: medic3
    entrypoint: python3 /app/system/leader/main.py
    environment:
      - NODE_ID=103
      - LOGGING_LEVEL=INFO
      - RING_SIZE=4
      - PYTHONPATH=/app
    networks:
      - system_network

networks:
  system_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
