version: '3.8'
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"  # Puerto para conexion con RabbitMQ
      - "15672:15672"  # Puerto para la interfaz de administracion
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"] # -f hace q curl falle silenciosamente si la web no funciona
      interval: 10s #verifica salud de rabbit each 10 s
      timeout: 5s # si rabbit no responde en 5s falla 
      retries: 10 # luego de 10 intentos => no es saludable

  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ./data/games.csv:/data/games.csv
      - ./data/dataset.csv:/data/dataset.csv
      - ./resultsExpect:/resultsExpect
      - ./results:/results
    environment:
      - NODE_ID=1
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - HOSTNAME=gateway
    entrypoint: python3 /app/client/main.py
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/system/controllers/gateway/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  filterbasic_1:
    container_name: filterbasic_1
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=3
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  filterbasic_2:
    container_name: filterbasic_2
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=4
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  filterbasic_3:
    container_name: filterbasic_3
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=5
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  selectQ1_1:
    container_name: selectQ1_1
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=6
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  selectQ1_2:
    container_name: selectQ1_2
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=7
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable        

  selectQ1_3:
    container_name: selectQ1_3
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=8
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable        

  platformcounter_1:
    container_name: platformcounter_1
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=platformcounter_1
      - NODE_ID=9
      - TOTAL_NODES=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  platformcounter_2:
    container_name: platformcounter_2
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=platformcounter_1
      - NODE_ID=10
      - TOTAL_NODES=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

#Es una unica instancia el reducer
  platformreducer:
    container_name: platformreducer
    image: platformreducer:latest
    entrypoint: python3 /app/system/controllers/reducers/platformReducer/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME="platformreducer"
      - NODE_ID=11
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy


  selectQ2345_1:
    container_name: selectq2345_1
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectq2345_1
      - NODE_ID=12
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectQ2345_2:
    container_name: selectq2345_2
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectq2345_2
      - NODE_ID=13
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectQ2345_3:
    container_name: selectq2345_3
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectq2345_3
      - NODE_ID=14
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy        

  filterGender_1:
    container_name: filtergender_1
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filtergender_1
      - NODE_ID=15
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy        

  filterGender_2:
    container_name: filtergender_2
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filtergender_2
      - NODE_ID=16
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy    
  
  filterGender_3:
    container_name: filtergender_3
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filtergender_3
      - NODE_ID=17
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterDecade_1:
    container_name: filterdecade_1
    image: filterdecade:latest
    entrypoint: python3 /app/system/controllers/filters/filterDecade/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterdecade_1
      - NODE_ID=18
      - TOTAL_NODES=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterDecade_2:
    container_name: filterdecade_2
    image: filterdecade:latest
    entrypoint: python3 /app/system/controllers/filters/filterDecade/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterdecade_2
      - NODE_ID=19
      - TOTAL_NODES=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  grouperTopAvgPlaytime:
    container_name: groupertopavgplaytime
    image: groupertopavgplaytime:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopAvgPlaytime/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=groupertopavgplaytime
      - NODE_ID=20
      - TOTAL_NODES=1
      - TOP_SIZE=10
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterScorePositive_1:
    container_name: filterscorepositive_1
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterscorepositive_1
      - NODE_ID=21
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterScorePositive_2:
    container_name: filterscorepositive_2
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterscorepositive_2
      - NODE_ID=22
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterScorePositive_3:
    container_name: filterscorepositive_3
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterscorepositive_3
      - NODE_ID=23
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectIDName_1:
    container_name: selectidname_1
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectidname_1
      - NODE_ID=25
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy


  selectIDName_2:
    container_name: selectidname_2
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectidname_2
      - NODE_ID=26
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectIDName_3:
    container_name: selectidname_3
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=selectidname_3
      - NODE_ID=27
      - TOTAL_NODES=3
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  monitorStorageQ3_1:
    container_name: monitorstorageq3_1
    image: monitorstorageq3:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ3/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=monitorstorageq3_1
      - NODE_ID=28
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy


  grouperTopPositiveReview:
    container_name: groupertoppositivereviews
    image: groupertoppositivereviews:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopReviewsPositiveIndie/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=groupertoppositivereviews
      - NODE_ID=29
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy


  filterScoreNegative_1:
    container_name: filterscorenegative_1
    image: filterscorenegative:latest
    entrypoint: python3 /app/system/controllers/filters/filterScoreNegative/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterscorenegative_1
      - NODE_ID=30
      - TOTAL_NODES=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterScoreNegative_2:
    container_name: filterscorenegative_2
    image: filterscorenegative:latest
    entrypoint: python3 /app/system/controllers/filters/filterScoreNegative/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterscorenegative_2
      - NODE_ID=31
      - TOTAL_NODES=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  monitorStorageQ4_1:
    container_name: monitorstorageq4_1
    image: monitorstorageq4:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ4/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=monitorstorageq4_1
      - NODE_ID=33
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterReviewsEnglish:
    container_name: filterreviewsenglish_1
    image: filterreviewsenglish:latest
    entrypoint: python3 /app/system/controllers/filters/filterReviewsEnglish/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=filterreviewsenglish_1
      - NODE_ID=34
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  monitorStorageQ5_1:
    container_name: monitorstorageq5_1
    image: monitorstorageq5:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ5/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=monitorstorageq5_1
      - NODE_ID=35
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  grouperPercentile_1:
    container_name: grouperpercentile_1
    image: grouperpercentile:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperPercentile/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_NAME=grouperpercentile_1
      - NODE_ID=36
      - TOTAL_NODES=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy


networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
