
version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Puerto para conexion con RabbitMQ
      - "15672:15672"  # Puerto para la interfaz de administracion
    networks:
      - testing_net

  input:
    container_name: input
    build:
      context: ./input
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  output:
    container_name: output
    build:
      context: ./output
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  platformreducer:
    container_name: platformreducer
    build:
      context: ./platformreducer
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  sortertop10averageplaytime:
    container_name: sortertop10averageplaytime
    build:
      context: ./sortertop10averageplaytime
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  groupertop5reviewsposindie:
    container_name: groupertop5reviewsposindie
    build:
      context: ./groupertop5reviewsposindie
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  gamein90thpercentile:
    container_name: gamein90thpercentile
    build:
      context: ./gamein90thpercentile
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterbasic_1:
    container_name: filterbasic_1
    build:
      context: ./filterbasic
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  selectq1_1:
    container_name: selectq1_1
    build:
      context: ./selectq1
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  platformcounter_1:
    container_name: platformcounter_1
    build:
      context: ./platformcounter
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filtergender_1:
    container_name: filtergender_1
    build:
      context: ./filtergender
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterdecade2010_1:
    container_name: filterdecade2010_1
    build:
      context: ./filterdecade2010
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  selectidname_1:
    container_name: selectidname_1
    build:
      context: ./selectidname
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  selectq345_1:
    container_name: selectq345_1
    build:
      context: ./selectq345
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterscorepositive_1:
    container_name: filterscorepositive_1
    build:
      context: ./filterscorepositive
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterreviewenglish_1:
    container_name: filterreviewenglish_1
    build:
      context: ./filterreviewenglish
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterscore50kpositives_1:
    container_name: filterscore50kpositives_1
    build:
      context: ./filterscore50kpositives
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  filterscorenegative_1:
    container_name: filterscorenegative_1
    build:
      context: ./filterscorenegative
      dockerfile: Dockerfile
    networks:
      - testing_net
    depends_on:
      - rabbitmq

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
