version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbit:latest
    ports:
      - "5672:5672"  # Puerto para conexion con RabbitMQ
      - "15672:15672"  # Puerto para la interfaz de administracion
    networks:
      - system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"] # -f hace q curl falle silenciosamente si la web no funciona
      interval: 10s #verifica salud de rabbit each 10 s
      timeout: 5s # si rabbit no responde en 5s falla 
      retries: 10 # luego de 10 intentos => no es saludable

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /app/client/main.py
    volumes:
      - ./data/games.csv:/data/games.csv
      - ./data/dataset.csv:/data/dataset.csv
      - ./resultsExpect:/resultsExpect
      - ./results:/results
    environment:
      - NODE_ID=1
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - HOSTNAME=gateway
      - PERCENT_OF_FILE_FOR_USE=0.1
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started

  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/system/controllers/gateway/main.py 
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=2
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy  # Espera hasta que RabbitMQ esté saludable

  filterbasic_1:
    container_name: filterbasic_1
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=3
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterbasic_2:
    container_name: filterbasic_2
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=4
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterbasic_3:
    container_name: filterbasic_3
    image: filterbasic:latest
    entrypoint: python3 /app/system/controllers/filters/filterBasic/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=5
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectq1_1:
    container_name: selectq1_1
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=6
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectq1_2:
    container_name: selectq1_2
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=7
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectq1_3:
    container_name: selectq1_3
    image: selectq1:latest
    entrypoint: python3 /app/system/controllers/select/selectQ1/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=8
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  platformcounter_1:
    container_name: platformcounter_1
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=9
      - TOTAL_NODES=2 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  platformcounter_2:
    container_name: platformcounter_2
    image: platformcounter:latest
    entrypoint: python3 /app/system/controllers/groupers/platformCounter/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=10
      - TOTAL_NODES=2 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  platformreducer_1:
    container_name: platformreducer_1
    image: platformreducer:latest
    entrypoint: python3 /app/system/controllers/reducers/platformReducer/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=11
      - TOTAL_NODES=1 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectq2345_1:
    container_name: selectq2345_1
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=12
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectq2345_2:
    container_name: selectq2345_2
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=13
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectq2345_3:
    container_name: selectq2345_3
    image: selectq2345:latest
    entrypoint: python3 /app/system/controllers/select/selectQ2345/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=14
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filtergender_1:
    container_name: filtergender_1
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=15
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filtergender_2:
    container_name: filtergender_2
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=16
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filtergender_3:
    container_name: filtergender_3
    image: filtergender:latest
    entrypoint: python3 /app/system/controllers/filters/filterGender/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=17
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterdecade_1:
    container_name: filterdecade_1
    image: filterdecade:latest
    entrypoint: python3 /app/system/controllers/filters/filterDecade/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=18
      - TOTAL_NODES=2 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterdecade_2:
    container_name: filterdecade_2
    image: filterdecade:latest
    entrypoint: python3 /app/system/controllers/filters/filterDecade/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=19
      - TOTAL_NODES=2 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  groupertopavgplaytime_1:
    container_name: groupertopavgplaytime_1
    image: groupertopavgplaytime:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopAvgPlaytime/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=20
      - TOTAL_NODES=1 
      - TOP_SIZE=10
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterscorepositive_1:
    container_name: filterscorepositive_1
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=21
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterscorepositive_2:
    container_name: filterscorepositive_2
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=22
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterscorepositive_3:
    container_name: filterscorepositive_3
    image: filterscorepositive:latest
    entrypoint: python3 /app/system/controllers/filters/filterScorePositive/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=23
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectidname_1:
    container_name: selectidname_1
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=24
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectidname_2:
    container_name: selectidname_2
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=25
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  selectidname_3:
    container_name: selectidname_3
    image: selectidname:latest
    entrypoint: python3 /app/system/controllers/select/selectIDName/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=26
      - TOTAL_NODES=3 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  monitorstorageq3_1:
    container_name: monitorstorageq3_1
    image: monitorstorageq3:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ3/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=27
      - TOTAL_NODES=1 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  groupertoppositivereviews_1:
    container_name: groupertoppositivereviews_1
    image: groupertoppositivereviews:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperTopReviewsPositiveIndie/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=28
      - TOTAL_NODES=1 
      - TOP_SIZE=5
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterscorenegative_1:
    container_name: filterscorenegative_1
    image: filterscorenegative:latest
    entrypoint: python3 /app/system/controllers/filters/filterScoreNegative/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=29
      - TOTAL_NODES=2 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterscorenegative_2:
    container_name: filterscorenegative_2
    image: filterscorenegative:latest
    entrypoint: python3 /app/system/controllers/filters/filterScoreNegative/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=30
      - TOTAL_NODES=2 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  monitorstorageq4_1:
    container_name: monitorstorageq4_1
    image: monitorstorageq4:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ4/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=31
      - TOTAL_NODES=1 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  filterreviewsenglish_1:
    container_name: filterreviewsenglish_1
    image: filterreviewsenglish:latest
    entrypoint: python3 /app/system/controllers/filters/filterReviewsEnglish/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=32
      - TOTAL_NODES=1 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  monitorstorageq5_1:
    container_name: monitorstorageq5_1
    image: monitorstorageq5:latest
    entrypoint: python3 /app/system/controllers/storages/monitorStorageQ5/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=33
      - TOTAL_NODES=1 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  grouperpercentile_1:
    container_name: grouperpercentile_1
    image: grouperpercentile:latest
    entrypoint: python3 /app/system/controllers/groupers/grouperPercentile/main.py
    environment:
      - LOGGING_LEVEL=INFO
      - PYTHONPATH=/app
      - NODE_ID=34
      - TOTAL_NODES=1 
    networks:
      - system_network
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  system_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
