@startuml
|User|
start
:Crea un socket;
:Inicia una conexión y comienza a mandar datos;

|Servidor|
:Acepta la conexión y recibe datos;
:Encola los mensajes según el CSV correspondiente;
   |Games Parser|
   :Recibe cada juego y parsea su ID;
   |Gender Filter|
   :Filtra los juegos indies;
   |Year Filter|
   :Filtra los juegos de la decada 2010;
   |Query resolver|
   :Acumula el top 10 de juegos con mas tiempo historico;
   |User|
   :Recibe resultado de la query;
@enduml