@startuml
|User|
start
   |Games Parser|
   :Recibe cada juego y parsea su ID;
   |Platform Filter|
   :Extrae el dato de que plataformas pueden correr en un juego;
   |Platform Resolver|
   :Acumula la cantidad de juegos por plataforma;
   |User|
   :Recibe resultado de la query;
@enduml