@startuml
   |Games Parser|
start
   :Recibe cada juego y parsea su ID;
   |Gender Filter|
   :Filtra los juegos indie;
   |Top Sorter|
   :Recibe juegos y se queda con los 5\ncon más reseñas positivas;
   |Query resolver|
   :Acumula los juegos y se queda con los\nque tengan 50k reviews en ingles;
   |Server|
   :Recibe resultado de la query;
stop
@enduml