@startuml
|User|
start
:Crea un socket;
:Inicia una conexión y comienza a mandar datos;

|Servidor|
:Acepta la conexión y recibe datos;
if (Encola los mensajes según el CSV correspondiente) then
   |Reviews Parser|
   :Recibe cada review y parsea su ID;
else
   |Games Parser|
   :Recibe cada juego y parsea su ID;
   |Gender Filter|
   :Filtra los juegos shooter;
   |Reviews Filter|
   :Filtra los juegos con 50k reviews;
endif
   |Query resolver|
   :Acumula los juegos y se queda con los\nque tengan 50k reviews en ingles;
   |User|
   :Recibe resultado de la query;
@enduml