#!/usr/bin/python3
import zmq
import time
from random import randrange
#PUB-SUB, 1 Publisher y N subscriber.
context = zmq.Context()
# Socket de tipo PUB 
socket = context.socket(zmq.PUB)
# Hace el bind, se conecta como si fuera un server
socket.bind("tcp://*:5556") 
print("Starting Pub process")

while True:
    zipcode = randrange(1,4)
    temperature = randrange(-80, 135)
    relhumidity = randrange(10, 60)

    msg = "%i %i %i" % (zipcode, temperature, relhumidity)
    print("Sending string: {}".format(msg))
    # Enviamos el mensaje siempre del formato id, field1, field2, etc
    socket.send_string("%i %i %i" % (zipcode, temperature, relhumidity))
    time.sleep(1)
