@startuml
|User|
start
:Importar la libreria de middleware;
:instanciar un middleware e invocar un start();

|Middleware|
:Lee el directorio q contiene csv y\n obtiene chunks de tamaño equitativos;
:Envia usando ExchangeDirect el csv\n respectivo a trabajar para cada queue;

|ExchangeDirect|
:Por cada Mensaje asociado con un routing\n key lo pusheamos a la queue respectiva;

|NodoWorker|
:Recibe el csv a operar y realiza las consultas;

|User|
:Recibir estado del trabajo;
stop

@enduml