#!/usr/bin/python3
import zmq

context = zmq.Context()

#  Socket to talk to server
print("Connecting to hello world server")
# Le creamos un socket del tipo REQUEST!. 
socket = context.socket(zmq.REQ)

# socket.setsockopt(zmq.RCVTIMEO, 2000)
socket.connect("tcp://server:5555") # estamos dentro del compose server es la ip (dockercompose). 

#  Do 10 requests, waiting each time for a response
for request in range(10):
    print("Sending request {}".format(request))
    socket.send(b"Hello")

    #  Get the reply.
    message = socket.recv()
    print("Received reply %s [ %s ]" % (request, message))
